package identifiers;
//// default package
//// Generated 29-may-2017 19:54:34 by Hibernate Tools 5.2.1.Final
//
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AulaRecursosId generated by hbm2java
 */
@Embeddable
public class AulaRecursosId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idAula;
	private int idRecurso;

	public AulaRecursosId() {
	}

	public AulaRecursosId(int idAula, int idRecurso) {
		this.idAula = idAula;
		this.idRecurso = idRecurso;
	}

	@Column(name = "id_aula", nullable = false)
	public int getIdAula() {
		return this.idAula;
	}

	public void setIdAula(int idAula) {
		this.idAula = idAula;
	}

	@Column(name = "id_recurso", nullable = false)
	public int getIdRecurso() {
		return this.idRecurso;
	}

	public void setIdRecurso(int idRecurso) {
		this.idRecurso = idRecurso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AulaRecursosId))
			return false;
		AulaRecursosId castOther = (AulaRecursosId) other;

		return (this.getIdAula() == castOther.getIdAula()) && (this.getIdRecurso() == castOther.getIdRecurso());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAula();
		result = 37 * result + this.getIdRecurso();
		return result;
	}

}
