package identifiers;

// default package
// Generated 29-may-2017 19:54:34 by Hibernate Tools 5.2.1.Final

import java.sql.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReservasId generated by hbm2java
 */
@Embeddable
public class ReservasId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idPersonal;
	private int idAula;
	private Date fechaReserva;
	private int idHorario;

	public ReservasId() {
	}

	public ReservasId(int idPersonal, int idAula, Date fechaReserva,int idHorario) {
		this.idPersonal = idPersonal;
		this.idAula = idAula;
		this.fechaReserva = fechaReserva;
		this.idHorario = idHorario;
	}

	@Column(name = "id_personal", nullable = false)
	public int getIdPersonal() {
		return this.idPersonal;
	}

	public void setIdPersonal(int idPersonal) {
		this.idPersonal = idPersonal;
	}

	@Column(name = "id_aula", nullable = false)
	public int getIdAula() {
		return this.idAula;
	}

	public void setIdAula(int idAula) {
		this.idAula = idAula;
	}

	@Column(name = "fecha_reserva", nullable = false, length = 10)
	public Date getFechaReserva() {
		return this.fechaReserva;
	}

	public void setFechaReserva(Date fechaReserva) {
		this.fechaReserva = fechaReserva;
	}

	@Column(name = "id_horario", nullable = false)
	public int getIdHorario() {
		return this.idHorario;
	}

	public void setIdHorario(int idHorario) {
		this.idHorario = idHorario;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((fechaReserva == null) ? 0 : fechaReserva.hashCode());
		result = prime * result + idAula;
		result = prime * result + idHorario;
		result = prime * result + idPersonal;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ReservasId other = (ReservasId) obj;
		if (fechaReserva == null) {
			if (other.fechaReserva != null)
				return false;
		} else if (!fechaReserva.equals(other.fechaReserva))
			return false;
		if (idAula != other.idAula)
			return false;
		if (idHorario != other.idHorario)
			return false;
		if (idPersonal != other.idPersonal)
			return false;
		return true;
	}

	

}
