package entities;
// Generated 28-sep-2017 21:02:46 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name = "horario", catalog = "gestorrecursos")
public class Horario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Date inicio;
	private Date fin;
	private Set<Reservas> reservases = new HashSet<Reservas>(0);

	public Horario() {
	}

	public Horario(Date inicio, Date fin) {
		this.inicio = inicio;
		this.fin = fin;
	}

	public Horario(Date inicio, Date fin, Set<Reservas> reservases) {
		this.inicio = inicio;
		this.fin = fin;
		this.reservases = reservases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "inicio", nullable = false, length = 8)
	public Date getInicio() {
		return this.inicio;
	}

	public void setInicio(Date inicio) {
		this.inicio = inicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "fin", nullable = false, length = 8)
	public Date getFin() {
		return this.fin;
	}

	public void setFin(Date fin) {
		this.fin = fin;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "horario")
	@JsonIgnore
	public Set<Reservas> getReservases() {
		return this.reservases;
	}

	public void setReservases(Set<Reservas> reservases) {
		this.reservases = reservases;
	}

}