package entities;

import static javax.persistence.GenerationType.IDENTITY;


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Personal generated by hbm2java
 */
@Entity
@Table(name = "personal", catalog = "gestorrecursos")
public class Personal implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Permisos permisos;
	private String nombre;
	private String apellidos;
	private String username;
	private String pass;
	private Set<Reservas> reservases = new HashSet<Reservas>(0);
	private Set<Aula> aulas = new HashSet<Aula>(0);

	public Personal() {
	}

	public Personal(String nombre, String apellidos) {
		this.nombre = nombre;
		this.apellidos = apellidos;
	}

	public Personal(Permisos permisos, String nombre, String apellidos, Set<Reservas> reservases, Set<Aula> aulas) {
		this.permisos = permisos;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.reservases = reservases;
		this.aulas = aulas;
	}

	public Personal( Permisos permisos, String nombre, String apellidos, String username, String pass) {
		super();

		this.permisos = permisos;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.username = username;
		this.pass = pass;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_permiso")
	public Permisos getPermisos() {
		return this.permisos;
	}

	public void setPermisos(Permisos permisos) {
		this.permisos = permisos;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellidos", nullable = false)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "personal")
	@JsonIgnore
	public Set<Reservas> getReservases() {
		return this.reservases;
	}

	public void setReservases(Set<Reservas> reservases) {
		this.reservases = reservases;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "personal")
	@JsonIgnore
	public Set<Aula> getAulas() {
		return this.aulas;
	}

	public void setAulas(Set<Aula> aulas) {
		this.aulas = aulas;
	}
	@Column(name = "pass", nullable = true)
	public String getPass() {
		return pass;
	}

	public String getUsername() {
		return username;
	}
	@Column(name = "username", nullable = false)
	public void setUsername(String username) {
		this.username = username;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

}
