package entities;

// default package
// Generated 29-may-2017 19:54:34 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Recursos generated by hbm2java
 */
@Entity
@Table(name = "recursos", catalog = "gestorrecursos")
public class Recursos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String nombre;
	private String descripcion;
	private Set<AulaRecursos> aulaRecursoses = new HashSet<AulaRecursos>(0);

	public Recursos() {
	}

	public Recursos(String nombre) {
		this.nombre = nombre;
	}

	public Recursos(String nombre, String descripcion) {
		this.nombre = nombre;
		this.descripcion = descripcion;
	
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recursos")
	@JsonIgnore
	public Set<AulaRecursos> getAulaRecursoses() {
		return this.aulaRecursoses;
	}

	public void setAulaRecursoses(Set<AulaRecursos> aulaRecursoses) {
		this.aulaRecursoses = aulaRecursoses;
	}

}
